/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import DAL.ModuloConexaoLocal;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jader
 */
public class Login extends javax.swing.JFrame {

    private static void setBorder(TitledBorder createTitledBorder) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() throws Exception {

        String sql = "select *from tb_usuarios where email=? and senha=? and perfil=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            pst.setString(2, pswSenha.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String perfil = rs.getString(3);
                if (perfil.equals("Suporte")||perfil.equals("Administrador")) {
                    Inicio inicio = new Inicio();
                    inicio.setVisible(true);
                    inicio.menuPaciente.setEnabled(true);
                    inicio.menuCadUsuarios.setEnabled(true);
                    inicio.menuAgendamento.setEnabled(true);
                    inicio.lblUsuario.setForeground(Color.red);
                    
                } else {
                    Inicio inicio = new Inicio();
                    inicio.setVisible(true);
                }
                
                //Inicio.lblUsuario.setText(rs.getString(2));
                
                this.dispose();//fecha tela de login depois de logar
                conexao.close();//fecha conexao com banco de dados
            } else {
                JOptionPane.showMessageDialog(null, "Usuario e/ou Senha Inválido(s)!");
            }
        } catch (SQLException e) {
            /*JOptionPane.showMessageDialog(null,"Erro ao conectar ao banco de dados" + e.getMessage());*/
            throw new SQLException ("Erro ao conectar ao banco de dados" + e.getMessage());
        }
    }
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 203, 254));
        setForeground(java.awt.Color.blue);
        setResizable(false);
        setSize(new java.awt.Dimension(590, 380));
        getContentPane().setLayout(null);

        btnSair.setBackground(new java.awt.Color(50, 203, 254));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon logout.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(20, 273, 60, 80);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(230, 205, 210, 37);

        pswSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pswSenha.setBorder(null);
        getContentPane().add(pswSenha);
        pswSenha.setBounds(230, 260, 220, 35);

        btnEntrar.setBackground(new java.awt.Color(0, 0, 153));
        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(260, 310, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/background login_full.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 600, 420);

        setSize(new java.awt.Dimension(614, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            logar();
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    protected javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
